name: Build and Test for All OS and Go Versions

on:
  push:
    branches:
      - prod
  pull_request:

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
        go-version: '1.21.x'

    steps:
      # 检出代码
      - name: Checkout Code
        uses: actions/checkout@v4

      # 设置 Go 环境
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go-version }}

      # 显示环境信息
      - name: Display Environment Info
        run: |
          echo "Operating System: ${{ matrix.os }}"
          echo "Go Version: $(go version)"

      # 缓存 Go 模块
      - name: Cache Go Modules
        uses: actions/cache@v3
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ matrix.go-version }}-modules-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-${{ matrix.go-version }}-modules-

      # 安装依赖
      - name: Install Dependencies
        run: go mod tidy

      # 构建项目
      - name: Build
        run: go build ./...

      # 运行测试
      - name: Run Tests
        run: go test ./...

      # 针对 Windows 打包构建产物
      - name: Archive Build (Windows Only)
        if: ${{ matrix.os == 'windows-latest' }}
        run: |
          mkdir -p build
          tar -czvf build/windows_build.tar.gz ./main.exe

      # 上传构建产物
      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: build-${{ matrix.os }}-${{ matrix.go-version }}
          path: ./build
